effect:
  description: Controls the effect settings of WLED
  fields:
    entity_id:
      description: Name of the WLED light entity.
      example: "light.wled"
    effect:
      description: Name or ID of the WLED light effect.
      example: "Rainbow"
    intensity:
      description: Intensity of the effect. Number between 0 and 255.
      example: 100
    palette:
      description: Name or ID of the WLED light palette.
      example: "Tiamat"
    speed:
      description: Speed of the effect. Number between 0 (slow) and 255 (fast).
      example: 150
    reverse:
      description: Reverse the effect. Either true to reverse or false otherwise.
      example: false
preset:
  description: Calls a preset on the WLED device
  fields:
    entity_id:
      description: Name of the WLED light entity.
      example: "light.wled"
    preset:
      description: ID of the WLED preset
      example: 6
